server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  datasource:
    driver-class-name: org.h2.Driver    # ?????? ????? H2 DB? ??
    url: jdbc:h2:mem:test;MODE=MySQL    # H2 ???? ??????? MySQL ?? ??? ?? (????)
    username: sa                        # ?????? ?? ? ?? ??? ??
    password:                           # ?????? ?? ???? (?? ??)
  h2:
    console:
      enabled: true   # H2 ?????? ??? ????? ?????? ??????? ??? ? ??? ?
  sql:
    init:
      data-locations:
        - classpath:db/data.sql  # ?????? ??? ? ??? ??? ?? SQL ??? ?? (data.sql)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10 #한번에 들고오는 갯수 설정
    defer-datasource-initialization: true

  output:
    ansi:
      enabled: always